# Generated by Django 5.2.4 on 2025-08-01 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="股票名稱"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvestmentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.IntegerField(
                        default="default_id", unique=True, verbose_name="交易ID"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("BUY", "買"), ("SELL", "賣")],
                        default="BUY",
                        max_length=10,
                        verbose_name="交易類型",
                    ),
                ),
                ("buy_date", models.DateField(verbose_name="買進日期")),
                ("buy_price", models.FloatField(verbose_name="買進價")),
                ("quantity", models.IntegerField(verbose_name="張數")),
                ("buy_amount", models.IntegerField(verbose_name="買進金額")),
                ("fee_rate", models.FloatField(verbose_name="手續費率")),
                ("fee_amount", models.FloatField(verbose_name="手續費金額")),
                ("total_cost", models.IntegerField(verbose_name="總成本")),
                (
                    "sell_date",
                    models.DateField(blank=True, null=True, verbose_name="賣出日期"),
                ),
                (
                    "sell_amount",
                    models.IntegerField(blank=True, null=True, verbose_name="賣出總額"),
                ),
                (
                    "net_profit",
                    models.IntegerField(blank=True, null=True, verbose_name="淨利"),
                ),
                (
                    "profit_rate",
                    models.FloatField(blank=True, null=True, verbose_name="獲利率"),
                ),
                (
                    "annual_return_rate",
                    models.FloatField(blank=True, null=True, verbose_name="年化報酬率"),
                ),
                (
                    "holding_days",
                    models.IntegerField(blank=True, null=True, verbose_name="持有天數"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments",
                        to="stocks.stock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DividendRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="張數")),
                ("payout_date", models.DateField(verbose_name="發放日期")),
                (
                    "dividend_per_share",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="每股股利"
                    ),
                ),
                (
                    "total_dividend",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="總股利"
                    ),
                ),
                (
                    "actual_income",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="實際進帳"
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="手續費"
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dividends",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "股利紀錄",
                "verbose_name_plural": "股利紀錄",
            },
        ),
    ]
